DROP DATABASE IF EXISTS blog;
CREATE DATABASE blog;
DROP TABLE IF EXISTS articles;
CREATE TABLE `articles` (
  `id` INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(255) NOT NULL,
  `body` TEXT NOT NULL,
  `category_id` INT DEFAULT NULL,
  `created_at` DATETIME NOT NULL,
  `updated_at` DATETIME NOT NULL
) DEFAULT CHARACTER SET=utf8mb4;